version: '3.8'
services:
  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX4HwVmsxKPCDjwMtyKVge5oLd9t42
    volumes:
#      - cache:/data
      - ./docker/redis/data:/data

  # uncomment the following if PostgreSQL db is needed
#  db:
#    image: postgres:alpine
#    environment:
#      - POSTGRES_USER=ukubenet
#      - POSTGRES_PASSWORD=p@ssWord
#      - POSTGRES_DB=metadata
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-db:/var/lib/postgresql/data
#      - ./docker/db/data:/var/lib/postgresql/data

volumes:
#  postgres-db:
  cache:
#    driver: local