deployer:
    adapter: json_file
    path: /../../../data
    entitysubpath: entity/json
    registersubpath: register

metadata:
    adapter: json_file
    path: /../../../data
    metasubpath: metadata/json
    tmplsubpath: metadata/tmpl

frontend:
    adapter: svelte
