deployer:
    adapter: json_file
    path: ""
    entitysubpath: entity/json
    registersubpath: register

metadata:
    adapter: json_file
    path: ""
    metasubpath: metadata/json
    tmplsubpath: metadata/tmpl

